import Layout from "@/components/Layout";
import Head from "next/head";
import { GiTennisCourt } from "react-icons/gi";
import { BsShop } from "react-icons/bs";
import { FaHandshake } from "react-icons/fa";
import Image from "next/image";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Avesta Padelcenter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main
          className="bg-cover bg-center h-screen z-[-1]"
          style={{ backgroundImage: "url('/apc-biljard.jpg')" }}
        >
          <div className="bg-black h-screen bg-opacity-40 pt-16">
            <div className="container mx-auto">
              {session ? (
                <h1 className="text-center text-2xl font-extrabold">
                  Välkommen {session.user?.name}!
                </h1>
              ) : (
                <h1 className="text-center text-2xl font-extrabold">
                  Välkommen till APC
                </h1>
              )}
              {/* <button className="absolute top-[50%] left-[50%] w-28 h-10 bg-gradient-to-r from-red-700 to-red-600 rounded">
                Bli medlem
              </button>
              <button className="absolute top-[50%] left-[20%] w-28 h-10 bg-gradient-to-r from-red-700 to-red-600 rounded">
                Kontaka oss
              </button> */}
            </div>
          </div>
        </main>
        <section className="w-screen flex flex-col laptop:flex-row bg-slate-100 text-slate-900">
          <article className="w-screen flex flex-col justify-center items-center p-4 gap-4">
            <div className="w-14 h-14 bg-red-600 rounded-[50%] flex justify-center items-center">
              <GiTennisCourt color="white" size={28} />
            </div>
            <h2 className="text-2xl font-extrabold">Om hallen</h2>
            <ul className="list-disc w-[225px]">
              <li>14 meter i takhöjd</li>
              <li>5 dubbelbanor</li>
              <li>1 singelbana</li>
              <li>Golfstudio</li>
              <li>Utomhusbanor vid Avesta GK</li>
            </ul>
          </article>
          <article className="w-screen flex flex-col justify-center items-center bg-slate-200 p-4 gap-4">
            <div className="w-14 h-14 bg-red-600 rounded-[50%] flex justify-center items-center">
              <BsShop color="white" size={28} />
            </div>
            <h2 className="text-2xl font-extrabold">Butik</h2>
            <p className="text-center">
              I vår butik hittar du en variation av olika varumärken
            </p>
            <ul className="list-disc w-[225px]">
              <li>Racket</li>
              <li>Skor</li>
              <li>Kläder</li>
            </ul>
          </article>
          <article className="w-screen flex flex-col justify-center items-center p-4 gap-4">
            <div className="w-14 h-14 bg-red-600 rounded-[50%] flex justify-center items-center">
              <FaHandshake color="white" size={28} />
            </div>
            <h2 className="text-2xl font-extrabold">Medlemskap</h2>
            <p>Medlemskapet kommer med en massa fördelar</p>
            <ul className="list-disc w-[225px]">
              <li>Gratis inträde i seriespelet och sommarstegen</li>
              <li>Boka tider 3 veckor i förtid (icke-medlem är 2)</li>
              <li>10% rabatt vid alla bokningar</li>
              <li>APC t-shirt (1 per år)</li>
            </ul>
            <Link
              href={`/medlemskap`}
              className="btn border-none shadow-xl bg-gradient-to-r from-red-700 to-red-600"
            >
              Bli medlem
            </Link>
          </article>
        </section>
        <section className="w-screen flex flex-col laptop:flex-row bg-red-900 text-slate-100 items-center text-center">
          <article className="w-full flex flex-col items-center py-6 px-4">
            <h2 className="text-2xl font-extrabold">Golfstudio</h2>
            <p className="mb-4 h-12">Bokas som vanligt i MATCHi</p>

            <Image
              src={"/Golfstudio.jpg"}
              width={300}
              height={300}
              alt="golfstudio"
              className="rounded-xl"
            />
          </article>
          <article className="w-full bg-red-800 flex flex-col items-center py-6 px-4">
            <h2 className="text-2xl font-extrabold">Café</h2>
            <p className="mb-4 h-12">Hungrig? Ingen fara, vi har tilltugg.</p>

            <Image
              src={"/Pizza.jpg"}
              width={300}
              height={300}
              alt="pizza"
              className="rounded-xl"
            />
          </article>
          <article className="w-full flex flex-col items-center py-6 px-4">
            <h2 className="text-2xl font-extrabold">Aktiviteter</h2>
            <p className="mb-4">
              Håll utkik på MATCHi då vi frekvent lägger ut olika aktiviteter!
            </p>
            <Image
              src={"/Frukostpadel.png"}
              width={300}
              height={300}
              alt="frukostpadel"
              className="rounded-xl"
            />
          </article>
        </section>
      </Layout>
    </>
  );
}
