import Layout from "@/components/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Avesta Padelcenter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main
          className="bg-cover bg-center h-screen z-[-1]"
          style={{ backgroundImage: "url('/apc-biljard.jpg')" }}
        >
          <div className="bg-black h-screen bg-opacity-40 pt-16">
            <div className="container mx-auto">
              <h1 className="text-center text-2xl font-extrabold">
                Välkommen till APC
              </h1>
              {/* <button className="absolute top-[50%] left-[50%] w-28 h-10 bg-gradient-to-r from-red-700 to-red-600 rounded">
                Bli medlem
              </button>
              <button className="absolute top-[50%] left-[20%] w-28 h-10 bg-gradient-to-r from-red-700 to-red-600 rounded">
                Kontaka oss
              </button> */}
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}
